'use client';

import Image from 'next/image';
import { useRouter } from 'next/navigation';
import { useState } from 'react';
import { Briefcase, Heart, Repeat2, Search } from 'lucide-react';
import { BASE_DEVS, EXPERTISES, type Developer } from '@/lib/data/developers';
import { BASE_PROJECTS } from '@/lib/data/projects';
import { COMMUNITIES, HERO_AVATARS, TESTIMONIALS, TWEETS } from '@/lib/data/content';
import { DeveloperCard, ProjectCard } from './Cards';
import { QuoteIcon } from './icons';
import { Rule, SectionHeading } from './SectionHeading';

export function HomeClient() {
  const router = useRouter(); const [heroQuery, setHeroQuery] = useState(''); const [heroExpertise, setHeroExpertise] = useState('Titre'); const [projectOffset, setProjectOffset] = useState(0); const [memberOffset, setMemberOffset] = useState(0);
  const featuredProjects = Array.from({ length: 3 }, (_, i) => BASE_PROJECTS[(projectOffset + i) % BASE_PROJECTS.length]);
  const members = Array.from({ length: 4 }, (_, i) => BASE_DEVS[(memberOffset + i) % 8]);
  const search = (e: React.FormEvent) => { e.preventDefault(); const p = new URLSearchParams(); if (heroQuery) p.set('q', heroQuery); if (heroExpertise !== 'Titre') p.set('expertise', heroExpertise); router.push(`/developers?${p.toString()}`); };
  return <>
    <section className="mx-auto grid max-w-container grid-cols-[repeat(auto-fit,minmax(min(100%,420px),1fr))] items-center gap-[clamp(32px,5vw,56px)] px-[clamp(16px,4vw,24px)] py-[clamp(40px,7vw,84px)] pb-[clamp(48px,7vw,90px)]">
      <div><h1 className="m-0 text-[clamp(38px,5.4vw,60px)] font-extrabold leading-[1.08] tracking-[-.03em]">Open Source Community by cameroonian developers.</h1><p className="mt-6 max-w-[36em] text-[clamp(15px,1.3vw,17px)] leading-[1.65] text-muted-alt">Nunc scelerisque tincidunt elit. Vestibulum non mi ipsum. Cras pretium suscipit tellus sit amet aliquet.</p><p className="mb-3.5 mt-[34px] text-base font-semibold">Looking for experienced developers ?</p><form onSubmit={search} className="flex max-w-[680px] flex-col gap-2 rounded-xl border border-border-soft bg-white p-2.5 shadow-search sm:flex-row sm:flex-wrap sm:items-center"><div className="flex flex-1 items-center gap-2.5 px-1.5 sm:flex-[1_1_220px]"><Search size={20} className="shrink-0 text-blue"/><input value={heroQuery} onChange={(e)=>setHeroQuery(e.target.value)} placeholder="Search by Company, Languages..." className="min-w-0 flex-1 border-0 bg-transparent py-3 text-[15px] outline-none"/></div><div className="flex items-center gap-2 border-t border-border-soft pt-2 sm:contents sm:border-0 sm:pt-0"><select value={heroExpertise} onChange={(e)=>setHeroExpertise(e.target.value)} aria-label="Expertise" className="min-w-0 flex-1 border-0 bg-transparent px-2.5 py-3 text-[15px] text-muted-alt outline-none sm:flex-[0_1_150px] sm:border-l sm:border-border-soft">{EXPERTISES.map((e)=><option key={e}>{e}</option>)}</select><button className="shrink-0 rounded-btn bg-blue px-6 py-3.5 text-[15px] font-semibold text-white transition hover:-translate-y-0.5 hover:bg-blue-dark sm:px-[30px]">Search</button></div></form></div>
      <div className="relative hidden min-h-[clamp(340px,42vw,520px)] lg:block">{HERO_AVATARS.map((a, i) => <div key={a.src} className="absolute" style={{ left:a.left, top:a.top, width:a.size, height:a.size, animation:`bob ${5+i*.4}s ease-in-out ${a.d}s infinite` }}><div className="absolute -inset-[18px] rounded-[28px] bg-[radial-gradient(circle,rgba(59,118,239,.22),rgba(59,118,239,0)_70%)]"/><Image src={a.src} alt="" fill sizes="150px" className="relative rounded-[22px] object-cover shadow-[0_8px_24px_rgba(16,24,40,.14)]"/></div>)}</div>
    </section>
    <Supporters/>
    <section className="bg-blue-50"><div className="mx-auto max-w-container px-[clamp(16px,4vw,24px)] py-[clamp(56px,8vw,96px)]"><SectionHeader title="Discover the most recent projects!" cta="See more projects" onPrev={()=>setProjectOffset((projectOffset + BASE_PROJECTS.length - 1) % BASE_PROJECTS.length)} onNext={()=>setProjectOffset(projectOffset+1)} go={()=>router.push('/projects')} /><div className="grid grid-cols-[repeat(auto-fit,minmax(min(100%,300px),1fr))] gap-6">{featuredProjects.map((p)=><ProjectCard key={p.id} project={p}/>)}</div></div></section>
    <Testimonials/>
    <section className="bg-grey-50"><div className="mx-auto max-w-container px-[clamp(16px,4vw,24px)] py-[clamp(56px,8vw,96px)]"><SectionHeader title="Discover all the members of our community" cta="See more member" onPrev={()=>setMemberOffset((memberOffset+7)%8)} onNext={()=>setMemberOffset(memberOffset+1)} go={()=>router.push('/developers')} /><div className="grid grid-cols-[repeat(auto-fit,minmax(min(100%,220px),1fr))] gap-[22px]">{members.map((d)=><MemberLink key={d.id} dev={d}/>)}</div></div></section>
    <Tweets/>
    <SupportCTA/>
    <Communities/>
  </>;
}
function Supporters(){ return <section className="bg-navy"><div className="mx-auto flex max-w-container flex-wrap items-center justify-between gap-[clamp(20px,4vw,48px)] px-[clamp(16px,4vw,24px)] py-[26px]"><span className="text-[15px] text-muted-light-5">They support us:</span><span className="text-[19px] font-bold tracking-[.14em] text-muted-light-4">APLEONA</span><span className="text-[19px] font-semibold text-muted-light-4">rocketseat</span><span className="text-[22px] font-bold tracking-[-.04em] text-muted-light-4">facebook</span><span className="text-[22px] font-medium tracking-[-.02em] text-muted-light-4">Google</span><span className="text-xl font-semibold text-muted-light-4">Linked<span className="rounded-[3px] bg-muted-light-4 px-1 font-bold text-navy">in</span></span></div></section>; }
function SectionHeader({ title, cta, onPrev, onNext, go }: { title:string; cta:string; onPrev:()=>void; onNext:()=>void; go:()=>void }) { return <div className="mb-10 grid grid-cols-[repeat(auto-fit,minmax(min(100%,340px),1fr))] items-end gap-6"><div><SectionHeading className="max-w-[14em]">{title}</SectionHeading><p className="m-0 text-base text-muted">Quisque suscipit ipsum est, eu venenatis leo ornare eget.</p></div><div className="flex flex-wrap gap-3"><button onClick={go} className="rounded-btn bg-blue px-[30px] py-4 text-[15px] font-semibold text-white transition hover:-translate-y-0.5 hover:bg-blue-dark">{cta}</button><Arrow label="Previous" onClick={onPrev}>←</Arrow><Arrow label="Next" onClick={onNext}>→</Arrow></div></div>; }
function Arrow({ label, onClick, children }: { label:string; onClick:()=>void; children: React.ReactNode }) { return <button aria-label={label} onClick={onClick} className="h-[52px] w-[52px] rounded-full border-[1.5px] border-blue-200 bg-blue-100 text-blue transition hover:bg-[#CBDCFA]">{children}</button>; }
function Testimonials(){ return <section className="bg-white"><div className="mx-auto max-w-container px-[clamp(16px,4vw,24px)] py-[clamp(56px,8vw,96px)]"><SectionHeading centered>Members of our community talk about it</SectionHeading><div className="mt-10 grid grid-cols-[repeat(auto-fit,minmax(min(100%,260px),1fr))] gap-[clamp(24px,3vw,36px)]">{TESTIMONIALS.map((t,i)=><div key={t.name} className="space-y-6">{i===1 && <Quote text={t.text} name={t.name} role={t.role}/>}<div className="relative aspect-[6/5] overflow-hidden rounded-[10px]"><Image src={t.img} alt={t.name} fill sizes="360px" className="object-cover saturate-[1.08]"/></div>{i!==1 && <Quote text={t.text} name={t.name} role={t.role}/>}</div>)}</div></div></section>; }
function Quote({ text, name, role }: { text:string; name:string; role:string }) { return <div className="flex gap-4"><QuoteIcon className="mt-1 h-[26px] w-[34px] shrink-0"/><div><p className="m-0 text-[15.5px] leading-[1.6] text-ink-70">{text}</p><p className="mt-3 text-[14.5px] text-muted-alt"><strong className="uppercase tracking-[.02em] text-blue">{name}</strong> · {role}</p></div></div>; }
function MemberLink({ dev }: { dev: Developer }) { return <DeveloperCard dev={dev} href={`/developers?dev=${dev.id}`}/>; }
function Tweets(){ return <section id="tweets" className="bg-navy"><div className="mx-auto max-w-container px-[clamp(16px,4vw,24px)] py-[clamp(56px,8vw,96px)]"><div className="text-white"><SectionHeading centered>It&apos;s raining tweets</SectionHeading></div><div className="mt-10 grid grid-cols-[repeat(auto-fit,minmax(min(100%,300px),1fr))] gap-5">{TWEETS.map((t,i)=><article key={i} className="rounded-card border border-white/10 bg-white/[.05] p-5 transition hover:-translate-y-1 hover:bg-white/[.09]"><div className="flex items-center gap-3"><Image src={t.img} alt="" width={42} height={42} className="rounded-full object-cover"/><div><h3 className="m-0 text-[15px] font-bold text-white">{t.name}</h3><p className="text-[13.5px] text-muted-light-4">{t.handle}</p></div></div><p className="mt-4 text-[14.5px] leading-[1.6] text-muted-light-6">{t.text}</p><div className="mt-5 flex gap-5 text-[13.5px] font-semibold text-muted-light-3"><span className="flex gap-1.5"><Repeat2 size={17}/>{t.rt}</span><span className="flex gap-1.5"><Heart size={17}/>{t.likes}</span></div></article>)}</div></div></section>; }
function SupportCTA(){ return <section id="support" className="bg-blue-50"><div className="mx-auto max-w-container px-[clamp(16px,4vw,24px)] py-[clamp(56px,8vw,96px)]"><div className="grid grid-cols-[repeat(auto-fit,minmax(min(100%,320px),1fr))] overflow-hidden rounded-support bg-white shadow-rest"><div className="relative min-h-[280px]"><Image src="/assets/support.png" alt="" fill sizes="560px" className="object-cover"/></div><div className="p-[clamp(28px,5vw,58px)]"><h2 className="text-[clamp(30px,3.6vw,42px)] font-extrabold leading-[1.14] tracking-[-.03em] text-blue">Support the OSS Cameroon community</h2><p className="mt-5 text-base leading-[1.7] text-muted-alt">Quisque suscipit ipsum est, eu venenatis leo ornare eget. Ut porta facilisis elementum.</p><button className="mt-7 rounded-btn bg-blue px-[30px] py-4 text-[15px] font-semibold text-white transition hover:-translate-y-0.5 hover:bg-blue-dark">Support the community</button></div></div></div></section>; }
function Communities(){ return <section className="bg-white"><div className="mx-auto max-w-container px-[clamp(16px,4vw,24px)] py-[clamp(56px,8vw,96px)] text-center"><SectionHeading centered>Other open source community</SectionHeading><p className="mx-auto mt-0 max-w-[62ch] text-base leading-[1.7] text-muted-alt">Quisque suscipit ipsum est, eu venenatis leo ornare eget. Ut porta facilisis elementum.</p><div className="mt-10 grid grid-cols-[repeat(auto-fit,minmax(min(100%,290px),1fr))] gap-6 text-left">{COMMUNITIES.map((c)=><article key={c.name} className="overflow-hidden rounded-card border border-border bg-white"><div className="relative flex min-h-[190px] items-center justify-center bg-white"><Image src={c.img} alt={c.name} width={210} height={130} className="max-h-[130px] max-w-[62%] object-contain"/></div><div className="bg-grey-100 p-6"><h3 className="text-[20px] font-bold">{c.name}</h3><p className="mt-3 min-h-[54px] text-[14.5px] leading-[1.6] text-muted-alt">{c.desc}</p><button className="mt-5 flex items-center gap-2 rounded-btn bg-blue px-6 py-3.5 text-[15px] font-semibold text-white transition hover:-translate-y-0.5 hover:bg-blue-dark">Join us →</button></div></article>)}</div></div></section>; }
