'use client';

import Image from 'next/image';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useState } from 'react';
import { Search } from 'lucide-react';
import { BASE_DEVS, EXPERTISES, type Developer } from '@/lib/data/developers';
import { BASE_PROJECTS } from '@/lib/data/projects';
import { COMMUNITIES, HERO_AVATAR_DEFAULTS, HERO_AVATAR_POSITIONS, TESTIMONIALS } from '@/lib/data/content';
import { DeveloperCard, ProjectCard } from './Cards';
import { QuoteIcon } from './icons';
import { Rule, SectionHeading } from './SectionHeading';

export function HomeClient({ heroDevs = [], memberDevs = [] }: { heroDevs?: Developer[]; memberDevs?: Developer[] }) {
  const heroAvatars = HERO_AVATAR_POSITIONS.map((_, i) => heroDevs[i] ? { src: heroDevs[i].avatar, login: heroDevs[i].login } : { src: HERO_AVATAR_DEFAULTS[i], login: '' });
  const memberPool = memberDevs.length > 0 ? memberDevs : BASE_DEVS;
  const router = useRouter(); const [heroQuery, setHeroQuery] = useState(''); const [heroExpertise, setHeroExpertise] = useState('Titre'); const [projectOffset, setProjectOffset] = useState(0); const [memberOffset, setMemberOffset] = useState(0);
  const featuredProjects = Array.from({ length: 3 }, (_, i) => BASE_PROJECTS[(projectOffset + i) % BASE_PROJECTS.length]);
  const members = Array.from({ length: 4 }, (_, i) => memberPool[(memberOffset + i) % memberPool.length]);
  const search = (e: React.FormEvent) => { e.preventDefault(); const p = new URLSearchParams(); if (heroQuery) p.set('q', heroQuery); if (heroExpertise !== 'Titre') p.set('expertise', heroExpertise); router.push(`/developers?${p.toString()}`); };
  return <>
    <section className="mx-auto grid max-w-container grid-cols-[repeat(auto-fit,minmax(min(100%,420px),1fr))] items-center gap-[clamp(32px,5vw,56px)] px-[clamp(16px,4vw,24px)] py-[clamp(40px,7vw,84px)] pb-[clamp(48px,7vw,90px)]">
      <div><h1 className="m-0 text-[clamp(38px,5.4vw,60px)] font-extrabold leading-[1.08] tracking-[-.03em]">Open Source Community by cameroonian developers.</h1><p className="mt-6 max-w-[36em] text-[clamp(15px,1.3vw,17px)] leading-[1.65] text-muted-alt">Promoting the talent and know-how of Cameroonians by leveraging our technical knowledge to bring solutions to problems found in our society.</p><p className="mb-3.5 mt-[34px] text-base font-semibold">Looking for experienced developers ?</p><form onSubmit={search} className="flex max-w-[680px] flex-col gap-2 rounded-xl border border-border-soft bg-white p-2.5 shadow-search sm:flex-row sm:flex-wrap sm:items-center"><div className="flex flex-1 items-center gap-2.5 px-1.5 sm:flex-[1_1_220px]"><Search size={20} className="shrink-0 text-blue"/><input value={heroQuery} onChange={(e)=>setHeroQuery(e.target.value)} placeholder="Search by Company, Languages..." className="min-w-0 flex-1 border-0 bg-transparent py-3 text-[15px] outline-none"/></div><div className="flex items-center gap-2 border-t border-border-soft pt-2 sm:contents sm:border-0 sm:pt-0"><select value={heroExpertise} onChange={(e)=>setHeroExpertise(e.target.value)} aria-label="Expertise" className="min-w-0 flex-1 border-0 bg-transparent px-2.5 py-3 text-[15px] text-muted-alt outline-none sm:flex-[0_1_150px] sm:border-l sm:border-border-soft">{EXPERTISES.map((e)=><option key={e}>{e}</option>)}</select><button className="shrink-0 rounded-btn bg-blue px-6 py-3.5 text-[15px] font-semibold text-white transition hover:-translate-y-0.5 hover:bg-blue-dark sm:px-[30px]">Search</button></div></form></div>
      <div className="relative hidden min-h-[clamp(340px,42vw,520px)] lg:block">{HERO_AVATAR_POSITIONS.map((a, i) => { const av = heroAvatars[i]; const inner = <><div className="absolute -inset-[18px] rounded-[28px] bg-[radial-gradient(circle,rgba(59,118,239,.22),rgba(59,118,239,0)_70%)]"/><Image src={av.src} alt={av.login || ''} fill sizes="150px" className="relative rounded-[22px] object-cover shadow-[0_8px_24px_rgba(16,24,40,.14)]"/></>; return av.login ? <Link key={i} href={`https://github.com/${av.login}`} target="_blank" rel="noopener noreferrer" className="absolute block transition-transform hover:scale-110" style={{ left:a.left, top:a.top, width:a.size, height:a.size, animation:`bob ${5+i*.4}s ease-in-out ${a.d}s infinite` }}>{inner}</Link> : <div key={i} className="absolute" style={{ left:a.left, top:a.top, width:a.size, height:a.size, animation:`bob ${5+i*.4}s ease-in-out ${a.d}s infinite` }}>{inner}</div>; })}</div>
    </section>
    <Supporters/>
    <section className="bg-blue-50"><div className="mx-auto max-w-container px-[clamp(16px,4vw,24px)] py-[clamp(56px,8vw,96px)]"><SectionHeader title="Discover the most recent projects!" cta="See more projects" onPrev={()=>setProjectOffset((projectOffset + BASE_PROJECTS.length - 1) % BASE_PROJECTS.length)} onNext={()=>setProjectOffset(projectOffset+1)} go={()=>router.push('/projects')} /><div className="grid grid-cols-[repeat(auto-fit,minmax(min(100%,300px),1fr))] gap-6">{featuredProjects.map((p)=><ProjectCard key={p.id} project={p} href={p.html_url && p.html_url !== '#' ? p.html_url : `/projects?project=${p.name}`}/>)}</div></div></section>
    <Testimonials/>
    <section className="bg-grey-50"><div className="mx-auto max-w-container px-[clamp(16px,4vw,24px)] py-[clamp(56px,8vw,96px)]"><SectionHeader title="Discover all the members of our community" cta="See more member" onPrev={()=>setMemberOffset((memberOffset+7)%8)} onNext={()=>setMemberOffset(memberOffset+1)} go={()=>router.push('/developers')} /><div className="grid grid-cols-2 gap-3 sm:gap-[22px] md:grid-cols-[repeat(auto-fit,minmax(220px,1fr))]">{members.map((d)=><MemberLink key={d.id} dev={d}/>)}</div></div></section>
    <SupportCTA/>
    <Communities/>
  </>;
}
function Supporters(){ return <section className="bg-navy"><div className="mx-auto flex max-w-container flex-wrap items-center justify-center gap-[clamp(16px,3vw,48px)] px-[clamp(16px,4vw,24px)] py-[26px] sm:justify-between"><span className="w-full text-center text-[14px] text-muted-light-5 sm:w-auto sm:text-left sm:text-[15px]">They support us:</span><span className="text-[clamp(15px,2.5vw,19px)] font-bold tracking-[.14em] text-muted-light-4">glevosys</span><span className="text-[clamp(15px,2.5vw,19px)] font-semibold text-muted-light-4">idemaAI</span><span className="text-[clamp(16px,3vw,22px)] font-bold tracking-[-.04em] text-muted-light-4">genuka</span><span className="text-[clamp(16px,3vw,22px)] font-medium tracking-[-.02em] text-muted-light-4">atori.space</span><span className="text-[clamp(15px,2.5vw,20px)] font-semibold text-muted-light-4">atori.school</span></div></section>; }
function SectionHeader({ title, cta, onPrev, onNext, go }: { title:string; cta:string; onPrev:()=>void; onNext:()=>void; go:()=>void }) { return <div className="mb-10 grid grid-cols-[repeat(auto-fit,minmax(min(100%,340px),1fr))] items-end gap-6"><div><SectionHeading className="max-w-[14em]">{title}</SectionHeading><p className="m-0 text-base text-muted">Built by developers who collaborate, mentor, and ship together.</p></div><div className="flex flex-wrap gap-3"><button onClick={go} className="rounded-btn bg-blue px-[30px] py-4 text-[15px] font-semibold text-white transition hover:-translate-y-0.5 hover:bg-blue-dark">{cta}</button><Arrow label="Previous" onClick={onPrev}>←</Arrow><Arrow label="Next" onClick={onNext}>→</Arrow></div></div>; }
function Arrow({ label, onClick, children }: { label:string; onClick:()=>void; children: React.ReactNode }) { return <button aria-label={label} onClick={onClick} className="h-[52px] w-[52px] rounded-full border-[1.5px] border-blue-200 bg-blue-100 text-blue transition hover:bg-[#CBDCFA]">{children}</button>; }
function Testimonials(){ return <section className="bg-white"><div className="mx-auto max-w-container px-[clamp(16px,4vw,24px)] py-[clamp(56px,8vw,96px)]"><SectionHeading centered>Members of our community talk about it</SectionHeading><div className="mt-10 grid grid-cols-[repeat(auto-fit,minmax(min(100%,260px),1fr))] gap-[clamp(24px,3vw,36px)]">{TESTIMONIALS.map((t,i)=><div key={t.name} className="space-y-6">{i===1 && <Quote text={t.text} name={t.name} role={t.role}/>}<div className="relative aspect-[6/5] overflow-hidden rounded-[10px]"><Image src={t.img} alt={t.name} fill sizes="360px" className="object-cover saturate-[1.08]"/></div>{i!==1 && <Quote text={t.text} name={t.name} role={t.role}/>}</div>)}</div></div></section>; }
function Quote({ text, name, role }: { text:string; name:string; role:string }) { return <div className="flex gap-4"><QuoteIcon className="mt-1 h-[26px] w-[34px] shrink-0"/><div><p className="m-0 text-[15.5px] leading-[1.6] text-ink-70">{text}</p><p className="mt-3 text-[14.5px] text-muted-alt"><strong className="uppercase tracking-[.02em] text-blue">{name}</strong> · {role}</p></div></div>; }
function MemberLink({ dev }: { dev: Developer }) { return <DeveloperCard dev={dev} href={dev.github_url && dev.github_url !== '#' ? dev.github_url : `https://github.com/${dev.login}`}/>; }
function SupportCTA(){ return <section id="support" className="bg-blue-50"><div className="mx-auto max-w-container px-[clamp(16px,4vw,24px)] py-[clamp(56px,8vw,96px)]"><div className="grid grid-cols-[repeat(auto-fit,minmax(min(100%,320px),1fr))] overflow-hidden rounded-support bg-white shadow-rest"><div className="relative min-h-[200px] sm:min-h-[280px]"><Image src="/assets/support.png" alt="" fill sizes="(max-width:640px) 100vw, 560px" className="object-cover"/></div><div className="p-[clamp(28px,5vw,58px)]"><h2 className="text-[clamp(30px,3.6vw,42px)] font-extrabold leading-[1.14] tracking-[-.03em] text-blue">Support the OSS Cameroon community</h2><p className="mt-5 text-base leading-[1.7] text-muted-alt">Help us provide equipment, connectivity, and training to Cameroonian developers. Your support fuels open-source projects that solve real problems in our society.</p><a href="https://opencollective.com/osscameroon/contribute/backer-26797/checkout?interval=month&amount=2&name=&legalName=&email=" target="_blank" rel="noopener noreferrer" className="mt-7 inline-block rounded-btn bg-blue px-[30px] py-4 text-[15px] font-semibold text-white transition hover:-translate-y-0.5 hover:bg-blue-dark">Support the community</a></div></div></div></section>; }
function Communities(){ const featured = COMMUNITIES.filter(c => c.category === 'oss').slice(0, 3); return <section className="bg-white"><div className="mx-auto max-w-container px-[clamp(16px,4vw,24px)] py-[clamp(56px,8vw,96px)] text-center"><SectionHeading centered>Open source communities</SectionHeading><p className="mx-auto mt-0 max-w-[62ch] text-base leading-[1.7] text-muted-alt">Discover the vibrant ecosystem of tech communities building, sharing, and growing together across Cameroon.</p><div className="mt-10 grid grid-cols-[repeat(auto-fit,minmax(min(100%,290px),1fr))] gap-6 text-left">{featured.map((c)=><article key={c.name} className="flex h-full flex-col overflow-hidden rounded-card border border-border bg-white transition hover:-translate-y-1 hover:shadow-hover">{c.img ? <div className="relative flex h-[140px] shrink-0 items-center justify-center bg-white sm:h-[190px]"><Image src={c.img} alt={c.name} width={210} height={130} className="max-h-[100px] max-w-[62%] object-contain sm:max-h-[130px]"/></div> : <div className="flex h-[140px] shrink-0 items-center justify-center bg-blue-50 sm:h-[190px]"><span className="text-[32px] font-extrabold tracking-tight text-blue/20 sm:text-[42px]">{c.name.split(' ').map(w => w[0]).join('')}</span></div>}<div className="flex flex-1 flex-col bg-grey-100 p-6"><h3 className="truncate text-[20px] font-bold">{c.name}</h3><p className="mt-3 line-clamp-2 text-[14.5px] leading-[1.6] text-muted-alt">{c.desc}</p><div className="mt-auto pt-5">{c.url ? <Link href={c.url} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-2 rounded-btn bg-blue px-6 py-3.5 text-[15px] font-semibold text-white transition hover:-translate-y-0.5 hover:bg-blue-dark">Visit →</Link> : <span className="inline-flex items-center gap-2 rounded-btn bg-blue/60 px-6 py-3.5 text-[15px] font-semibold text-white">Coming soon</span>}</div></div></article>)}</div><Link href="/communities" className="mt-10 inline-flex rounded-btn border-[1.5px] border-blue px-[30px] py-4 text-[15px] font-semibold text-blue transition hover:-translate-y-0.5 hover:bg-blue hover:text-white">See all communities →</Link></div></section>; }
